import type { Review } from "./reviews";

const avatar = (id: string) => `/reviews/${id}.webp`;
const r1 = avatar("r1"), r2 = avatar("r2"), r3 = avatar("r3"), r4 = avatar("r4"), r5 = avatar("r5");
const r6 = avatar("r6"), r7 = avatar("r7"), r8 = avatar("r8"), r9 = avatar("r9"), r10 = avatar("r10");
const r11 = avatar("r11"), r12 = avatar("r12"), r13 = avatar("r13"), r14 = avatar("r14"), r15 = avatar("r15"), r16 = avatar("r16");
const f1 = avatar("f1"), f2 = avatar("f2"), f3 = avatar("f3"), f4 = avatar("f4"), f5 = avatar("f5"), f6 = avatar("f6"), f7 = avatar("f7");
const f8 = avatar("f8"), f9 = avatar("f9"), f10 = avatar("f10"), f11 = avatar("f11"), f12 = avatar("f12"), f13 = avatar("f13"), f14 = avatar("f14"), f15 = avatar("f15"), f16 = avatar("f16");
const m1 = avatar("m1"), m2 = avatar("m2"), m3 = avatar("m3"), m4 = avatar("m4"), m5 = avatar("m5"), m6 = avatar("m6"), m7 = avatar("m7");
const m8 = avatar("m8"), m9 = avatar("m9"), m10 = avatar("m10"), m11 = avatar("m11"), m12 = avatar("m12"), m13 = avatar("m13"), m14 = avatar("m14"), m15 = avatar("m15"), m16 = avatar("m16");

export const POOL_BG: Review[] = [
  { name: "Елена Р.", city: "София", age: 52, photo: r1, gender: "f", rating: 5,
    text: "", daysAgo: 6, verified: true },
  { name: "Мария М.", city: "Пловдив", age: 38, photo: f1, gender: "f", rating: 5,
    text: "", daysAgo: 3, verified: true },
  { name: "Йоана С.", city: "Варна", age: 58, photo: r3, gender: "f", rating: 5,
    text: "", daysAgo: 9, verified: true },
  { name: "Андрея П.", city: "Бургас", age: 42, photo: f2, gender: "f", rating: 5,
    text: "", daysAgo: 5, verified: true },
  { name: "Ана Г.", city: "Русе", age: 60, photo: r5, gender: "f", rating: 5,
    text: "", daysAgo: 7, verified: true },
  { name: "Петър Х.", city: "Стара Загора", age: 65, photo: r2, gender: "m", rating: 5,
    text: "", daysAgo: 12, verified: true },
  { name: "Михаил Т.", city: "Плевен", age: 45, photo: m1, gender: "m", rating: 4,
    text: "", daysAgo: 18, verified: true },
  { name: "Иван Л.", city: "Велико Търново", age: 70, photo: r4, gender: "m", rating: 5,
    text: "", daysAgo: 22, verified: true },
  { name: "Андрей В.", city: "София", age: 55, photo: m2, gender: "m", rating: 4,
    text: "", daysAgo: 14, verified: true },
  { name: "Роберт Ф.", city: "Пловдив", age: 48, photo: r6, gender: "m", rating: 5,
    text: "", daysAgo: 11, verified: true },
  { name: "Соня Д.", city: "Варна", age: 47, photo: f3, gender: "f", rating: 5,
    text: "", daysAgo: 28, verified: true },
  { name: "Валерия Н.", city: "Бургас", age: 44, photo: r7, gender: "f", rating: 4,
    text: "", daysAgo: 15, verified: true },
  { name: "Дан К.", city: "Русе", age: 53, photo: m5, gender: "m", rating: 5,
    text: "", daysAgo: 26, verified: true },
  { name: "Павел Р.", city: "Стара Загора", age: 50, photo: m6, gender: "m", rating: 5,
    text: "", daysAgo: 8, verified: true },
  { name: "София З.", city: "Плевен", age: 39, photo: f4, gender: "f", rating: 5,
    text: "", daysAgo: 19, verified: true },
  { name: "Александър М.", city: "Велико Търново", age: 61, photo: m3, gender: "m", rating: 4,
    text: "", daysAgo: 31, verified: true },
  { name: "Марта Л.", city: "София", age: 46, photo: f5, gender: "f", rating: 5,
    text: "", daysAgo: 4, verified: true },
  { name: "Сергей Б.", city: "Пловдив", age: 57, photo: m4, gender: "m", rating: 5,
    text: "", daysAgo: 33, verified: true },
  { name: "Лаура Г.", city: "Варна", age: 51, photo: f6, gender: "f", rating: 4,
    text: "", daysAgo: 21, verified: true },
  { name: "Филип Д.", city: "Бургас", age: 49, photo: m7, gender: "m", rating: 5,
    text: "", daysAgo: 16, verified: true },
];

// Legacy RO persona pool (kept for scripts / migration).
export const POOL_RO: Review[] = [
  { name: "Elena R.", city: "София", age: 52, photo: r1, gender: "f", rating: 5,
    text: "", daysAgo: 6, verified: true },
  { name: "Maria M.", city: "Cluj-Napoca", age: 38, photo: f1, gender: "f", rating: 5,
    text: "", daysAgo: 3, verified: true },
  { name: "Ioana S.", city: "Iași", age: 58, photo: r3, gender: "f", rating: 5,
    text: "", daysAgo: 9, verified: true },
  { name: "Andreea P.", city: "Timișoara", age: 42, photo: f2, gender: "f", rating: 5,
    text: "", daysAgo: 5, verified: true },
  { name: "Ana G.", city: "Brașov", age: 60, photo: r5, gender: "f", rating: 5,
    text: "", daysAgo: 7, verified: true },
  { name: "Petru H.", city: "Constanța", age: 65, photo: r2, gender: "m", rating: 5,
    text: "", daysAgo: 12, verified: true },
  { name: "Mihai T.", city: "Craiova", age: 45, photo: m1, gender: "m", rating: 4,
    text: "", daysAgo: 18, verified: true },
  { name: "Ion L.", city: "Galați", age: 70, photo: r4, gender: "m", rating: 5,
    text: "", daysAgo: 22, verified: true },
  { name: "Andrei V.", city: "Oradea", age: 55, photo: m2, gender: "m", rating: 4,
    text: "", daysAgo: 14, verified: true },
  { name: "Robert F.", city: "Ploiești", age: 48, photo: r6, gender: "m", rating: 5,
    text: "", daysAgo: 11, verified: true },
  { name: "Sonia D.", city: "Sibiu", age: 47, photo: f3, gender: "f", rating: 5,
    text: "", daysAgo: 28, verified: true },
  { name: "Valeria N.", city: "Arad", age: 44, photo: r7, gender: "f", rating: 4,
    text: "", daysAgo: 15, verified: true },
  { name: "Dan C.", city: "Bacău", age: 53, photo: m5, gender: "m", rating: 5,
    text: "", daysAgo: 26, verified: true },
  { name: "Paul R.", city: "Pitești", age: 50, photo: m6, gender: "m", rating: 5,
    text: "", daysAgo: 8, verified: true },
  { name: "Sofia Z.", city: "Suceava", age: 39, photo: f4, gender: "f", rating: 5,
    text: "", daysAgo: 19, verified: true },
  { name: "Alexandru M.", city: "Târgu Mureș", age: 61, photo: m3, gender: "m", rating: 4,
    text: "", daysAgo: 31, verified: true },
  { name: "Martha L.", city: "Buzău", age: 46, photo: f5, gender: "f", rating: 5,
    text: "", daysAgo: 4, verified: true },
  { name: "Sergiu B.", city: "Brăila", age: 57, photo: m4, gender: "m", rating: 5,
    text: "", daysAgo: 33, verified: true },
  { name: "Laura G.", city: "Deva", age: 51, photo: f6, gender: "f", rating: 4,
    text: "", daysAgo: 21, verified: true },
  { name: "Filip D.", city: "Reșița", age: 49, photo: m7, gender: "m", rating: 5,
    text: "", daysAgo: 16, verified: true },
];

export const POOL_DE: Review[] = [
  { name: "Eva R.", city: "София", age: 52, photo: r1, gender: "f", rating: 5,
    text: "", daysAgo: 6, verified: true },
  { name: "Julia M.", city: "Hamburg", age: 38, photo: f1, gender: "f", rating: 5,
    text: "", daysAgo: 3, verified: true },
  { name: "Katharina S.", city: "München", age: 58, photo: r3, gender: "f", rating: 5,
    text: "", daysAgo: 9, verified: true },
  { name: "Lucia P.", city: "Köln", age: 42, photo: f2, gender: "f", rating: 5,
    text: "", daysAgo: 5, verified: true },
  { name: "Anna G.", city: "Frankfurt", age: 60, photo: r5, gender: "f", rating: 5,
    text: "", daysAgo: 7, verified: true },
  { name: "Peter H.", city: "Stuttgart", age: 65, photo: r2, gender: "m", rating: 5,
    text: "", daysAgo: 12, verified: true },
  { name: "Markus T.", city: "Düsseldorf", age: 45, photo: m1, gender: "m", rating: 4,
    text: "", daysAgo: 18, verified: true },
  { name: "Josef L.", city: "Leipzig", age: 70, photo: r4, gender: "m", rating: 5,
    text: "", daysAgo: 22, verified: true },
  { name: "Anton V.", city: "Dresden", age: 55, photo: m2, gender: "m", rating: 4,
    text: "", daysAgo: 14, verified: true },
  { name: "Robert F.", city: "Hannover", age: 48, photo: r6, gender: "m", rating: 5,
    text: "", daysAgo: 11, verified: true },
  { name: "Sonja D.", city: "Nürnberg", age: 47, photo: f3, gender: "f", rating: 5,
    text: "", daysAgo: 28, verified: true },
  { name: "Valeria N.", city: "Bremen", age: 44, photo: r7, gender: "f", rating: 4,
    text: "", daysAgo: 15, verified: true },
  { name: "David C.", city: "Essen", age: 53, photo: m5, gender: "m", rating: 5,
    text: "", daysAgo: 26, verified: true },
  { name: "Paul R.", city: "Dortmund", age: 50, photo: m6, gender: "m", rating: 5,
    text: "", daysAgo: 8, verified: true },
  { name: "Sophie Z.", city: "Bonn", age: 39, photo: f4, gender: "f", rating: 5,
    text: "", daysAgo: 19, verified: true },
  { name: "Alexander M.", city: "Karlsruhe", age: 61, photo: m3, gender: "m", rating: 4,
    text: "", daysAgo: 31, verified: true },
  { name: "Martha L.", city: "Münster", age: 46, photo: f5, gender: "f", rating: 5,
    text: "", daysAgo: 4, verified: true },
  { name: "Serge B.", city: "Augsburg", age: 57, photo: m4, gender: "m", rating: 5,
    text: "", daysAgo: 33, verified: true },
  { name: "Laura G.", city: "Wiesbaden", age: 51, photo: f6, gender: "f", rating: 4,
    text: "", daysAgo: 21, verified: true },
  { name: "Philipp D.", city: "Mainz", age: 49, photo: m7, gender: "m", rating: 5,
    text: "", daysAgo: 16, verified: true },
];

// Legacy IT persona pool (kept for potential future locales).
export const POOL_IT: Review[] = [
  { name: "Elena C.", city: "Roma", age: 52, photo: r1, gender: "f", rating: 5,
    text: "", daysAgo: 6, verified: true },
  { name: "Giulia B.", city: "Milano", age: 38, photo: f1, gender: "f", rating: 5,
    text: "", daysAgo: 3, verified: true },
  { name: "Francesca R.", city: "Napoli", age: 58, photo: r3, gender: "f", rating: 5,
    text: "", daysAgo: 9, verified: true },
  { name: "Chiara M.", city: "Torino", age: 42, photo: f2, gender: "f", rating: 5,
    text: "", daysAgo: 5, verified: true },
  { name: "Anna P.", city: "Bologna", age: 60, photo: r5, gender: "f", rating: 5,
    text: "", daysAgo: 7, verified: true },
  { name: "Marco R.", city: "Firenze", age: 65, photo: r2, gender: "m", rating: 5,
    text: "", daysAgo: 12, verified: true },
  { name: "Luca V.", city: "Genova", age: 45, photo: m1, gender: "m", rating: 4,
    text: "", daysAgo: 18, verified: true },
  { name: "Paolo G.", city: "Palermo", age: 70, photo: r4, gender: "m", rating: 5,
    text: "", daysAgo: 22, verified: true },
  { name: "Andrea S.", city: "Verona", age: 55, photo: m2, gender: "m", rating: 4,
    text: "", daysAgo: 14, verified: true },
  { name: "Roberto F.", city: "Bari", age: 48, photo: r6, gender: "m", rating: 5,
    text: "", daysAgo: 11, verified: true },
  { name: "Simona T.", city: "Padova", age: 47, photo: f3, gender: "f", rating: 5,
    text: "", daysAgo: 28, verified: true },
  { name: "Valentina L.", city: "Trieste", age: 44, photo: r7, gender: "f", rating: 4,
    text: "", daysAgo: 15, verified: true },
  { name: "Davide N.", city: "Parma", age: 53, photo: m5, gender: "m", rating: 5,
    text: "", daysAgo: 26, verified: true },
  { name: "Matteo C.", city: "Cagliari", age: 50, photo: m6, gender: "m", rating: 5,
    text: "", daysAgo: 8, verified: true },
  { name: "Sofia Z.", city: "Perugia", age: 39, photo: f4, gender: "f", rating: 5,
    text: "", daysAgo: 19, verified: true },
  { name: "Alessandro M.", city: "Brescia", age: 61, photo: m3, gender: "m", rating: 4,
    text: "", daysAgo: 31, verified: true },
  { name: "Martina L.", city: "Modena", age: 46, photo: f5, gender: "f", rating: 5,
    text: "", daysAgo: 4, verified: true },
  { name: "Stefano B.", city: "Reggio Calabria", age: 57, photo: m4, gender: "m", rating: 5,
    text: "", daysAgo: 33, verified: true },
  { name: "Laura G.", city: "Lecce", age: 51, photo: f6, gender: "f", rating: 4,
    text: "", daysAgo: 21, verified: true },
  { name: "Fabio D.", city: "Salerno", age: 49, photo: m7, gender: "m", rating: 5,
    text: "", daysAgo: 16, verified: true },
];
