/**
 * Golden shelf examples — feed title ROLE → catalog shelf (not brand lookup).
 */

export type ShelfClassificationFewShot = {
  feedTitle: string;
  goodShelf: string;
  goodRoleCs: string;
  badShelf: string;
  badRoleCs: string;
};

export const SHELF_CLASSIFICATION_FEW_SHOTS: ShelfClassificationFewShot[] = [
  {
    feedTitle: "detoxil — liver support capsules",
    goodShelf: "jatra",
    goodRoleCs: "máj és májdetox doplněk stravy",
    badShelf: "paraziti",
    badRoleCs: "proti parazitům produkt (parazita bucket)",
  },
  {
    feedTitle: "Diabexol — diabetes glucose control",
    goodShelf: "cukrovka",
    goodRoleCs: "vércukorszint szabályozó doplněk stravy",
    badShelf: "paraziti",
    badRoleCs: "proti parazitům",
  },
  {
    feedTitle: "Pest Repeller — ultrasonic rodent",
    goodShelf: "zahradni-naradi",
    goodRoleCs: "ultrazvukový odpuzovač hlodavců",
    badShelf: "paraziti",
    badRoleCs: "proti parazitům",
  },
  {
    feedTitle: "Menstrual Cup — feminine hygiene",
    goodShelf: "zdravi-zen",
    goodRoleCs: "újrahasználható menstruációs kehely",
    badShelf: "potence",
    badRoleCs: "férfi vitalitás doplněk stravy",
  },
  {
    feedTitle: "Rhino Correct — nose shape clip",
    goodShelf: "kosmeticke-nastroje",
    goodRoleCs: "nosní korektor / orrklipsz",
    badShelf: "zvetseni-penisu",
    badRoleCs: "gel na zvětšení penisu (Bucket enlargement)",
  },
  {
    feedTitle: "Rhino Gold — male enlargement gel",
    goodShelf: "zvetseni-penisu",
    goodRoleCs: "gel na zvětšení penisu",
    badShelf: "kosmeticke-nastroje",
    badRoleCs: "nosní korektor (același prefix Rhino, andere Rolle)",
  },
  {
    feedTitle: "Erectone Active",
    goodShelf: "potence",
    goodRoleCs: "kapsle na potenci",
    badShelf: "hemoroidy",
    badRoleCs: "proti hemoroidům doplněk stravy",
  },
  {
    feedTitle: "Proctonic Hemorrhoids Treatment",
    goodShelf: "hemoroidy",
    goodRoleCs: "proti hemoroidům doplněk stravy",
    badShelf: "potence",
    badRoleCs: "férfi vitalitás doplněk stravy",
  },
  {
    feedTitle: "AdCombo «detoxil» + Parasites + desc liver detox hepatic support",
    goodShelf: "jatra",
    goodRoleCs: "máj doplněk stravy",
    badShelf: "paraziti",
    badRoleCs: "proti parazitům (Bucket Parasites)",
  },
  {
    feedTitle: "AdCombo «detoxil» + Parasites + desc digestion tracto gastrointestinal",
    goodShelf: "traveni",
    goodRoleCs: "emésztés na podporu doplněk stravy",
    badShelf: "paraziti",
    badRoleCs: "proti parazitům",
  },
  {
    feedTitle: "AdCombo «Toxic OFF» + capsule (AdCombo bucket digestive)",
    goodShelf: "traveni",
    goodRoleCs: "proti parazitům kapsle",
    badShelf: "traveni",
    badRoleCs: "emésztés na podporu doplněk stravy",
  },
  {
    feedTitle: "KMA «Toxofil» + Pasozyty + desc papilomas verrugas",
    goodShelf: "papilomy",
    goodRoleCs: "doplněk stravy proti bradavicím",
    badShelf: "paraziti",
    badRoleCs: "proti parazitům",
  },
  {
    feedTitle: "KMA «Parazol» + Pasozyty, brodawki + desc anthelmintic tea / anthelmintischer ceai",
    goodShelf: "paraziti",
    goodRoleCs: "čaj proti parazitům",
    badShelf: "papilomy",
    badRoleCs: "doplněk stravy proti bradavicím (Bucket papillomas)",
  },
  {
    feedTitle: "KMA «Parazitel» + Pasozyty, brodawki + desc vermifuge capsules",
    goodShelf: "paraziti",
    goodRoleCs: "proti parazitům doplněk stravy",
    badShelf: "papilomy",
    badRoleCs: "szemölcs ellen",
  },
  {
    feedTitle: "AdCombo «Flybra» + desc sujetador push-up bra",
    goodShelf: "obleceni",
    goodRoleCs: "push-up podprsenka",
    badShelf: "domaci-vychytavky",
    badRoleCs: "háztartási cikk",
  },
  {
    feedTitle: "AdCombo «Pest Reject» + desc ultrasonic rodent repellent",
    goodShelf: "zahradni-naradi",
    goodRoleCs: "ultrazvukový odpuzovač hlodavců",
    badShelf: "paraziti",
    badRoleCs: "proti parazitům",
  },
  {
    feedTitle: "Balansulin — control automático de azúcar",
    goodShelf: "cukrovka",
    goodRoleCs: "vércukorszint szabályozó doplněk stravy",
    badShelf: "autodoplnky",
    badRoleCs: "autó kiegészítők («Auto» csapda)",
  },
  {
    feedTitle: "Insuvit — metabolismo automático glucosa",
    goodShelf: "cukrovka",
    goodRoleCs: "glükózanyagcsere doplněk stravy",
    badShelf: "autodoplnky",
    badRoleCs: "autópro",
  },
  {
    feedTitle: "GPS para Auto + sensor aparcamiento",
    goodShelf: "autodoplnky",
    goodRoleCs: "parkolássegítő / GPS járművekhez",
    badShelf: "cukrovka",
    badRoleCs: "doplněk stravy",
  },
  {
    feedTitle: "Funda parasol parabrisas Auto",
    goodShelf: "autodoplnky",
    goodRoleCs: "szélvédő takaró / védelem",
    badShelf: "modni-doplnky",
    badRoleCs: "általános kiegészítők",
  },
  {
    feedTitle: "detoxionis — cápsulas para desintoxicar",
    goodShelf: "detox",
    goodRoleCs: "test detox kapsle",
    badShelf: "autodoplnky",
    badRoleCs: "autópro (detox «car» csapda)",
  },
  {
    feedTitle: "NutriMix — kapsule proti nespečnosti",
    goodShelf: "chrapani",
    goodRoleCs: "alvás na podporu kapsle",
    badShelf: "hubnuti",
    badRoleCs: "testkontrola hmotnosti doplněk stravy (Bucket Abiau)",
  },
  {
    feedTitle: "Otto — kapsule za spomin",
    goodShelf: "stres",
    goodRoleCs: "kapsle na paměť a koncentraci",
    badShelf: "hubnuti",
    badRoleCs: "testkontrola hmotnosti doplněk stravy",
  },
  {
    feedTitle: "Nefro Aktiv — napitek za ledvice",
    goodShelf: "ledviny",
    goodRoleCs: "vese és húgyút na podporu ital",
    badShelf: "cystitida",
    badRoleCs: "csak hólyaggyulladásra (vese a címből figyelmen kívül)",
  },
  {
    feedTitle: "Hondroine — gel za sklepe",
    goodShelf: "klouby",
    goodRoleCs: "külsőleg alkalmazható kloubní gel",
    badShelf: "klouby",
    badRoleCs: "szájon át szedhető kloubní kapsle (hibás forma)",
  },
  {
    feedTitle: "Hondrofrost SI",
    goodShelf: "klouby",
    goodRoleCs: "kloubní gel",
    badShelf: "klouby",
    badRoleCs: "kloubní kapsle (csak joint-care bucket miatt)",
  },
  {
    feedTitle: "ArtiZynt — kapsule za sklepe",
    goodShelf: "klouby",
    goodRoleCs: "kloubní kapsle",
    badShelf: "klouby",
    badRoleCs: "kloubní gel (Feed nennt kapsule — oral lane)",
  },
  {
    feedTitle: "Wormax — kapsule proti parazitom",
    goodShelf: "paraziti",
    goodRoleCs: "proti parazitům kapsle",
    badShelf: "papilomy",
    badRoleCs: "doplněk stravy proti bradavicím (szemölcs bucket)",
  },
  {
    feedTitle: "Reishield — produkt na stawy",
    goodShelf: "klouby",
    goodRoleCs: "ízületi mobilitás doplněk stravy",
    badShelf: "jatra",
    badRoleCs: "máj doplněk stravy (Bucket liver-health)",
  },
  {
    feedTitle: "Para Clean — kapsule proti parazitom",
    goodShelf: "paraziti",
    goodRoleCs: "proti parazitům kapsle",
    badShelf: "domaci-potreby",
    badRoleCs: "háztartási / háztisztító cikk",
  },
  {
    feedTitle: "Otto — kapsule za spomin",
    goodShelf: "stres",
    goodRoleCs: "kapsle na paměť a koncentraci",
    badShelf: "detox",
    badRoleCs: "detox kapsle / curățare",
  },
  {
    feedTitle: "Reishield — kapsule za valgus",
    goodShelf: "vboceny-palec",
    goodRoleCs: "bütyök na podporu kapsle",
    badShelf: "vboceny-palec",
    badRoleCs: "ortopédiai eszköz / szilikon sín (greșite Form)",
  },
  {
    feedTitle: "Hemorolok — kapsule proti hemoroidom",
    goodShelf: "hemoroidy",
    goodRoleCs: "proti hemoroidům kapsle",
    badShelf: "hemoroidy",
    badRoleCs: "intim komfort doplněk stravy (eufemizmus)",
  },
  {
    feedTitle: "NOKTAL GEL — protiglivična raztopina",
    goodShelf: "plisen-nehtu",
    goodRoleCs: "körömgomba proti gel",
    badShelf: "anti-aging",
    badRoleCs: "anti-aging doplněk stravy / anti-aging ápolás",
  },
  {
    feedTitle: "Deep Inhale — čaj za pljuča",
    goodShelf: "dychaci-cesty",
    goodRoleCs: "tüdő és légzőszervi tea",
    badShelf: "stres",
    badRoleCs: "idegrendszer / stressz doplněk stravy",
  },
  {
    feedTitle: "ZFimuno — immunrendszer doplněk stravy",
    goodShelf: "imunita",
    goodRoleCs: "immunrendszer doplněk stravy",
    badShelf: "stres",
    badRoleCs: "memória és koncentráció doplněk stravy",
  },
  {
    feedTitle: "Cordyceps Pulse — ochi / vision / eye support",
    goodShelf: "zrak",
    goodRoleCs: "szem egészség kapsle",
    badShelf: "hubnuti",
    badRoleCs: "testkontrola hmotnosti doplněk stravy (márka «Pulse» ≠ fogyókúra)",
  },
  {
    feedTitle: "Reishield / Cordyceps — weight loss / abiau",
    goodShelf: "hubnuti",
    goodRoleCs: "kapsle na kontrolu hmotnosti",
    badShelf: "zrak",
    badRoleCs: "látás kapsle (más leíró a feedben)",
  },
  {
    feedTitle: "Proctonic — hemorrhoids cream",
    goodShelf: "hemoroidy",
    goodRoleCs: "krém proti hemoroidům",
    badShelf: "potence",
    badRoleCs: "férfi vitalitás kapsle",
  },
  {
    feedTitle: "Hondro G — spray valgus / hallux",
    goodShelf: "vboceny-palec",
    goodRoleCs: "sprej proti vbočeným palcům",
    badShelf: "klouby",
    badRoleCs: "ízületi korrektor / kloubní kapsle",
  },
  {
    feedTitle: "Cortitron — joint capsules / gel za sklepe",
    goodShelf: "klouby",
    goodRoleCs: "kloubní kapsle",
    badShelf: "hemoroidy",
    badRoleCs: "proti hemoroidům kapsle (más SKU)",
  },
  {
    feedTitle: "Cortitron — weight loss / odchudzanie",
    goodShelf: "hubnuti",
    goodRoleCs: "kapsle na kontrolu hmotnosti",
    badShelf: "hemoroidy",
    badRoleCs: "proti hemoroidům kapsle (más SKU)",
  },
  {
    feedTitle: "Cortitron — hemorrhoids / intimate comfort",
    goodShelf: "hemoroidy",
    goodRoleCs: "proti hemoroidům kapsle",
    badShelf: "klouby",
    badRoleCs: "kloubní kapsle",
  },
  {
    feedTitle: "ArtiZynt — gel za sklepe",
    goodShelf: "klouby",
    goodRoleCs: "kloubní gel",
    badShelf: "klouby",
    badRoleCs: "tautologikus gel (hibás fordítás)",
  },
  {
    feedTitle: "Motion Mat — massage mat",
    goodShelf: "domaci-vychytavky",
    goodRoleCs: "masážní podložka",
    badShelf: "krevni-tlak",
    badRoleCs: "vérnyomás doplněk stravy",
  },
  {
    feedTitle: "Uromexil — capsule (CPA TL bucket: Нутра: гипертония, description: potență)",
    goodShelf: "potence",
    goodRoleCs: "kapsle na potenci",
    badShelf: "krevni-tlak",
    badRoleCs: "vérnyomás doplněk stravy",
  },
  {
    feedTitle: "CardioBalance — capsule (CPA TL bucket: Нутра: потенция, description: tensiune)",
    goodShelf: "krevni-tlak",
    goodRoleCs: "vérnyomás kapsle",
    badShelf: "potence",
    badRoleCs: "kapsle na potenci",
  },
  {
    feedTitle: "Talorix — drops potency / potencja",
    goodShelf: "potence",
    goodRoleCs: "kapky na potenci",
    badShelf: "potence",
    badRoleCs: "férfi életenergia kapky (túl általános)",
  },
  {
    feedTitle: "Benaga Chaga — kapsule za kajenje",
    goodShelf: "odvykani-koureni",
    goodRoleCs: "kapsle na odvykání kouření",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (Shakes bucket csapda; márka önmagában nem osztályoz)",
  },
  {
    feedTitle: "Benaga — alkohol / alcohol dependency",
    goodShelf: "alkoholismus",
    goodRoleCs: "alkoholfüggőség na podporu kapsle",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (Shakes bucket csapda)",
  },
  {
    feedTitle: "Benaga — abiau / weight loss",
    goodShelf: "hubnuti",
    goodRoleCs: "kapsle na kontrolu hmotnosti",
    badShelf: "odvykani-koureni",
    badRoleCs: "kapsle na odvykání kouření (csak márka miatt — HIBÁS)",
  },
  {
    feedTitle: "Cordyceps — proti hemoroidom",
    goodShelf: "hemoroidy",
    goodRoleCs: "proti hemoroidům kapsle",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (Shakes bucket csapda)",
  },
  {
    feedTitle: "Reishield — proti hemoroidom",
    goodShelf: "hemoroidy",
    goodRoleCs: "proti hemoroidům kapsle",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (csak márka miatt — HIBÁS)",
  },
  {
    feedTitle: "Reishield — papilomi / papillomas",
    goodShelf: "papilomy",
    goodRoleCs: "papilloma proti kapsle",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (Shakes bucket csapda)",
  },
  {
    feedTitle: "Reishield — alkohol / alcohol dependency",
    goodShelf: "alkoholismus",
    goodRoleCs: "alkoholfüggőség na podporu kapsle",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (Shakes bucket csapda)",
  },
  {
    feedTitle: "Cordyceps — hemorrhoids treatment",
    goodShelf: "hemoroidy",
    goodRoleCs: "proti hemoroidům kapsle",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (Shakes bucket csapda)",
  },
  {
    feedTitle: "Cordyceps — hearing / sluh",
    goodShelf: "sluch",
    goodRoleCs: "hallás kapsle",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (Shakes bucket csapda)",
  },
  {
    feedTitle: "Reishield — shujšanje / weight loss",
    goodShelf: "hubnuti",
    goodRoleCs: "kapsle na kontrolu hmotnosti",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (csak partner bucket miatt)",
  },
  {
    feedTitle: "Reishield — respiratory bucket but weight SKU",
    goodShelf: "hubnuti",
    goodRoleCs: "kapsle na kontrolu hmotnosti",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (csak partner bucket miatt)",
  },
  {
    feedTitle: "DIY-Clock — ceas de designer",
    goodShelf: "modni-doplnky",
    goodRoleCs: "designer óra / DIY óra",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény (légzőszervi bucket csapda)",
  },
  {
    feedTitle: "Laser — lézer projektor",
    goodShelf: "domaci-vychytavky",
    goodRoleCs: "lézer projektor",
    badShelf: "dychaci-cesty",
    badRoleCs: "tüdő / légzőszervi készítmény",
  },
  {
    feedTitle: "RGB LED Lent — bandă LED",
    goodShelf: "domaci-vychytavky",
    goodRoleCs: "LED szalag / dekor világítás",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény",
  },
  {
    feedTitle: "BRANDCAMP — multifunkciós ásó",
    goodShelf: "zahradni-naradi",
    goodRoleCs: "multifunkciós ásó",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény",
  },
  {
    feedTitle: "lyuktömítő — lyukakpro",
    goodShelf: "domaci-vychytavky",
    goodRoleCs: "lyuk tömítő",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény",
  },
  {
    feedTitle: "Smart lampă senzor mișcare — solar wall lamp",
    goodShelf: "domaci-klima",
    goodRoleCs: "mozgásérzékelős napelemes lámpa",
    badShelf: "dychaci-cesty",
    badRoleCs: "légzőszervi készítmény",
  },
  {
    feedTitle: "Reishield — kapsule za spomin / memorsh",
    goodShelf: "stres",
    goodRoleCs: "kapsle na paměť a koncentraci",
    badShelf: "stres",
    badRoleCs: "anti-stress doplněk stravyk (partner bucket miatt — HIBÁS)",
  },
  {
    feedTitle: "Reishield — neuropat / neurosh",
    goodShelf: "stres",
    goodRoleCs: "kapsle proti neuropatii",
    badShelf: "stres",
    badRoleCs: "anti-stress doplněk stravyk (partner bucket miatt — HIBÁS)",
  },
  {
    feedTitle: "InsuLevel — Blutzucker / diabetes",
    goodShelf: "cukrovka",
    goodRoleCs: "vércukorszint szabályozó doplněk stravy",
    badShelf: "traveni",
    badRoleCs: "emésztés doplněk stravy (partner GI bucket)",
  },
  {
    feedTitle: "Balansulin — control de azúcar / digestive bucket",
    goodShelf: "cukrovka",
    goodRoleCs: "vércukorszint szabályozó doplněk stravy",
    badShelf: "traveni",
    badRoleCs: "emésztőrendszer doplněk stravy",
  },
  {
    feedTitle: "DM-Norm — glucose / glicemie",
    goodShelf: "cukrovka",
    goodRoleCs: "vércukorszint szabályozó doplněk stravy",
    badShelf: "imunita",
    badRoleCs: "immunitás / szervezet védelem doplněk stravy",
  },
  {
    feedTitle: "Cordyceps Pulse — rejuvsh / capsule anti-aging",
    goodShelf: "anti-aging",
    goodRoleCs: "anti-aging doplněk stravy",
    badShelf: "anti-aging",
    badRoleCs: "make-up základ / sminkkrém (szájon át kapsle, nem kozmetikum)",
  },
  {
    feedTitle: "Cordyceps — hemorsh / hemoroid (capsule)",
    goodShelf: "hemoroidy",
    goodRoleCs: "proti hemoroidům kapsle",
    badShelf: "hemoroidy",
    badRoleCs: "krém proti hemoroidům (szájon át kapsle, nem helyi)",
  },
  {
    feedTitle: "Neoflorax — othersh / Verdauung",
    goodShelf: "traveni",
    goodRoleCs: "emésztés na podporu doplněk stravy",
    badShelf: "traveni",
    badRoleCs: "jólét / általános közérzet produkt",
  },
  {
    feedTitle: "Hondro Sol — kloubní sprej",
    goodShelf: "klouby",
    goodRoleCs: "kloubní sprej",
    badShelf: "klouby",
    badRoleCs: "doplněk stravy / kloubní kapsle (hibás forma)",
  },
  {
    feedTitle: "Promicil — Nagelpilz Creme",
    goodShelf: "plisen-nehtu",
    goodRoleCs: "körömgomba proti krém",
    badShelf: "plisen-nehtu",
    badRoleCs: "kapsle proti plísni nehtů (greșite Form)",
  },
  {
    feedTitle: "Removio — Gel Papillome",
    goodShelf: "papilomy",
    goodRoleCs: "papilloma proti gel",
    badShelf: "papilomy",
    badRoleCs: "papilloma proti kapsle (hibás forma)",
  },
  {
    feedTitle: "Hondro Sol — spray valgus pe valgus-URL",
    goodShelf: "vboceny-palec",
    goodRoleCs: "sprej proti vbočeným palcům",
    badShelf: "klouby",
    badRoleCs: "kloubní produkt / ízületi korrektor",
  },
  {
    feedTitle: "Сухой очиститель для автомобиля",
    goodShelf: "autodoplnky",
    goodRoleCs: "suchý autočistič",
    badShelf: "sluch",
    badRoleCs: "produkt pro sluch (hibás hallás bucket)",
  },
  {
    feedTitle: "dry car cleaner / curățător auto",
    goodShelf: "autodoplnky",
    goodRoleCs: "suchý autočistič",
    badShelf: "sluch",
    badRoleCs: "hallás kapsle",
  },
  {
    feedTitle: "Mini USB vacuum cleaner",
    goodShelf: "domaci-vychytavky",
    goodRoleCs: "kompakt USB porszívó",
    badShelf: "sluch",
    badRoleCs: "produkt pro sluch",
  },
  {
    feedTitle: "Электрический очиститель косметических кистей",
    goodShelf: "kosmeticke-nastroje",
    goodRoleCs: "smink ecset tisztító eszköz",
    badShelf: "sluch",
    badRoleCs: "produkt pro sluch",
  },
  {
    feedTitle: "Venzen — BB cushion / fond de ten",
    goodShelf: "anti-aging",
    goodRoleCs: "cushion make-up",
    badShelf: "sluch",
    badRoleCs: "produkt pro sluch (hallás bucket)",
  },
  {
    feedTitle: "Curling iron — hair styler",
    goodShelf: "osobni-pece",
    goodRoleCs: "hajvasaló",
    badShelf: "sluch",
    badRoleCs: "produkt pro sluch",
  },
  {
    feedTitle: "LED face mask — skincare device",
    goodShelf: "kosmeticke-nastroje",
    goodRoleCs: "LED arcmaszk",
    badShelf: "sluch",
    badRoleCs: "produkt pro sluch",
  },
  {
    feedTitle: "Eyebrow powder — pudră sprâncene",
    goodShelf: "anti-aging",
    goodRoleCs: "szemöldök púder",
    badShelf: "zrak",
    badRoleCs: "szem doplněk stravy",
  },
  {
    feedTitle: "Knee — knee brace / genunchier",
    goodShelf: "klouby",
    goodRoleCs: "kolenní ortéza / térdvédő",
    badShelf: "krevni-tlak",
    badRoleCs: "vérnyomás doplněk stravy",
  },
  {
    feedTitle: "Rhino Correct — nose shape clip",
    goodShelf: "kosmeticke-nastroje",
    goodRoleCs: "nosní korektor",
    badShelf: "domaci-vychytavky",
    badRoleCs: "háztartási kütyü",
  },
  {
    feedTitle: "Benaga — testosterone boost",
    goodShelf: "potence",
    goodRoleCs: "tesztoszteron / férfi vitalitás kapsle",
    badShelf: "domaci-potreby",
    badRoleCs: "háztartási produkt",
  },
  {
    feedTitle: "Vermixin — antiparasitic capsules",
    goodShelf: "paraziti",
    goodRoleCs: "proti parazitům kapsle",
    badShelf: "imunita",
    badRoleCs: "immunitás doplněk stravy",
  },
  {
    feedTitle: "Cleorix — parasite cleanse",
    goodShelf: "paraziti",
    goodRoleCs: "proti parazitům kapsle",
    badShelf: "imunita",
    badRoleCs: "immunitás doplněk stravy",
  },
  {
    feedTitle: "Gigant — enlargement gel",
    goodShelf: "zvetseni-penisu",
    goodRoleCs: "gel na zvětšení penisu",
    badShelf: "potence",
    badRoleCs: "potencia gel",
  },
  {
    feedTitle: "Pest Reject — ultrasonic rodent repellent",
    goodShelf: "zahradni-naradi",
    goodRoleCs: "ultrazvukový odpuzovač hlodavců",
    badShelf: "paraziti",
    badRoleCs: "proti parazitům / jólét",
  },
  {
    feedTitle: "Balancio — (csak márka, balancioloss landing)",
    goodShelf: "hubnuti",
    goodRoleCs: "kapsle na kontrolu hmotnosti",
    badShelf: "domaci-potreby",
    badRoleCs: "jólét produkt",
  },
  {
    feedTitle: "Neoflorax — (csak márka, neoflorax othersh landing)",
    goodShelf: "traveni",
    goodRoleCs: "emésztés na podporu doplněk stravy",
    badShelf: "other",
    badRoleCs: "napi jólét produkt",
  },
  {
    feedTitle: "Benaga Chaga — (csak márka, benagachaga othersh)",
    goodShelf: "traveni",
    goodRoleCs: "emésztés na podporu doplněk stravy",
    badShelf: "domaci-potreby",
    badRoleCs: "háztartási / jólét produkt",
  },
  {
    feedTitle: "Cordyceps Pulse — (csak márka, rejuvsh landing)",
    goodShelf: "anti-aging",
    goodRoleCs: "anti-aging doplněk stravy",
    badShelf: "other",
    badRoleCs: "jólét produkt",
  },
  {
    feedTitle: "Cordyceps — (csak márka, household bucket)",
    goodShelf: "varies-by-landing",
    goodRoleCs: "kapsle [niche a landing URL-ből]",
    badShelf: "other",
    badRoleCs: "jólét produkt",
  },
  {
    feedTitle: "Щипцы для завивки волос — плойка",
    goodShelf: "osobni-pece",
    goodRoleCs: "hajvasaló",
    badShelf: "sluch",
    badRoleCs: "hallás kapsle / produkt pro sluch",
  },
  {
    feedTitle: "бигуди для волос",
    goodShelf: "osobni-pece",
    goodRoleCs: "hajcsavaró",
    badShelf: "sluch",
    badRoleCs: "hallás doplněk stravy",
  },
  {
    feedTitle: "Stubble Beard — триммер для бороды",
    goodShelf: "osobni-pece",
    goodRoleCs: "szakállvágó trimmer",
    badShelf: "sluch",
    badRoleCs: "produkt pro sluch",
  },
  {
    feedTitle: "Secret Model — жидкие колготки",
    goodShelf: "obleceni",
    goodRoleCs: "alakformáló harisnya",
    badShelf: "sluch",
    badRoleCs: "hallás doplněk stravy",
  },
  {
    feedTitle: "карандаш для отбеливания зубов",
    goodShelf: "osobni-pece",
    goodRoleCs: "fogfehérítő toll",
    badShelf: "sluch",
    badRoleCs: "hallás kapsle",
  },
  {
    feedTitle: "AirCalm — аромаувлажнитель",
    goodShelf: "domaci-klima",
    goodRoleCs: "aromaterápiás párásító",
    badShelf: "sluch",
    badRoleCs: "hallás doplněk stravy",
  },
];

export function buildShelfClassificationGuideCS(): string {
  const examples = SHELF_CLASSIFICATION_FEW_SHOTS.map(
    (s) =>
      `- «${s.feedTitle}» → «${s.goodShelf}» («${s.goodRoleCs}»)\n` +
      `    HIBÁS: «${s.badShelf}» («${s.badRoleCs}»)`,
  ).join("\n");

  return `=== PÉLDÁK FEED CÍM → KATEGÓRIA (produktszerep alapján, nem márka) ===
A márka nem határozza meg a kategóriát; a cím és feed leírója (produkttípus) igen.
Ugyanaz a márka különböző kategóriákban is lehet — olvasd a leírót.

${examples}

Szabály: a cím szerepe és a partner leírása (categories + description) határozza meg a kategóriát, nem a feed általános bucket-je.
A márka önmagában (leíró nélkül) nem osztályoz — Benaga, Cordyceps, Reishield esetén olvasd a landinget.
Vegyes «paraziták + szemölcsök» bucketnél a produktforma alapján válassz (čaj proti parazitům/kapsle vs. szemölcs), ne a bucket «szemölcs» szava alapján.
A «légzőszervi» / «hallás» / «immunitás» bucket gyakran más niche SKU-kat tartalmaz — a cím végét olvasd, ne a bucket-et.
KMA «hallás» bucket — a produkt címét olvasd, ne a bucket-et; kütyü/kozmetikum ≠ hallás doplněk stravy.
«household» / «other» / «othersh» bucket — olvasd a landing URL-t és címét, ne a márkát. SOHA «jólét produkt» orvosi landingű doplněk stravyhöz.`;
}
