/** SERP-aligned commercial primary keywords for CZ supplement hubs. */

export const SUPPLEMENT_PRIMARY_KW: Record<string, string> = {
  "klouby": "doplňky stravy na klouby",
  "krevni-tlak": "doplňky stravy na krevní tlak",
  "krecove-zily": "přípravky na křečové žíly",
  "cukrovka": "doplňky stravy na cukrovku",
  "detox": "detoxikace organismu",
  "potence": "doplňky stravy na potenci",
  "hubnuti": "doplňky stravy na hubnutí",
  "prostata": "doplňky stravy na prostatu",
  "zrak": "doplňky stravy na zrak",
  hemoroidy: "doplňky stravy na hemoroidy",
  "zdravi-zen": "doplňky stravy pro ženy",
  "stres": "doplňky stravy na stres",
  cystitida: "doplňky stravy na cystitidu",
  paraziti: "doplňky stravy na parazity",
  "plisen-nehtu": "doplňky stravy na plíseň nehtů",
  sluch: "doplňky stravy na sluch",
  traveni: "doplňky stravy na trávení",
  lupenka: "doplňky stravy na lupénku",
  alkoholismus: "doplňky stravy při odvykání alkoholu",
  "odvykani-koureni": "doplňky stravy na odvykání kouření",
  "vboceny-palec": "přípravky na vbočený palec",
  "vypadavani-vlasu": "doplňky stravy na vlasy",
  "zvetseni-penisu": "přípravky na zvětšení penisu",
  "zvetseni-prsou": "doplňky stravy na zvětšení prsou",
  papilomy: "přípravky na papilomy",
  "anti-aging": "doplňky stravy anti-aging",
  "jatra": "doplňky stravy na játra",
  "ledviny": "doplňky stravy na ledviny",
  "dychaci-cesty": "doplňky stravy na dýchací cesty",
  imunita: "doplňky stravy na imunitu",
  "chrapani": "přípravky proti chrápání",
};
