/**
 * Final Czech Republicn pass for RO AI prompt modules: renames, phrase translation, core constants.
 * Run: node scripts/czechize-cz-ai.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

const RENAMES = [
  ["buildInventionPolicyBlockDE", "buildInventionPolicyBlockRO"],
  ["buildShortFieldsGuideDE", "buildShortFieldsGuideRO"],
  ["buildGermanOutputGuideFaqDE", "buildCzech RepublicnOutputGuideFaqRO"],
  ["buildGermanOutputGuideDE", "buildCzech RepublicnOutputGuideRO"],
  ["buildNonMedicalBlockDE", "buildNonMedicalBlockRO"],
  ["buildStructureSpecCompactDE", "buildStructureSpecCompactRO"],
  ["buildStructureSpecDE", "buildStructureSpecRO"],
  ["buildDescHtmlToolHintDE", "buildDescHtmlToolHintRO"],
  ["buildToolSchemaDE", "buildToolSchemaRO"],
  ["buildFaqToolSchemaDE", "buildFaqToolSchemaRO"],
  ["buildFaqUserPromptDE", "buildFaqUserPromptRO"],
  ["buildUserPromptDE", "buildUserPromptRO"],
  ["buildPainFirstVocabularyGuideDE", "buildPainFirstVocabularyGuideCS"],
  ["buildCatalogShelfGuideDE", "buildCatalogShelfGuideRO"],
  ["buildNoPhotoCopyGuideDE", "buildNoPhotoCopyGuideRO"],
  ["buildDescriptorStyleGuideDE", "buildDescriptorStyleGuideRO"],
  ["buildFeedTitleCleanGuideDE", "buildFeedTitleCleanGuideRO"],
  ["buildProductRoleGuideDE", "buildProductRoleGuideRO"],
  ["buildProductIntentGuideDE", "buildProductIntentGuideRO"],
  ["buildShelfClassificationGuideDE", "buildShelfClassificationGuideRO"],
  ["TRANSLATE_SYSTEM_DE", "TRANSLATE_SYSTEM_CS"],
  ["German prompt builders", "Constructori de prompturi românești"],
  ["category-descriptors.de", "category-descriptors.ro"],
  ["problem-vocabulary.de", "problem-vocabulary.ro"],
  ["shelf-classification.examples.de", "shelf-classification.examples.ro"],
  ["feed-title-clean.de", "feed-title-clean.ro"],
  ["product-intent.de", "product-intent.ro"],
  ["product-role.de", "product-role.ro"],
];

const PHRASES = [
  ["=== AUSGABE AUF DEUTSCH (description_html + FAQ) ===", "=== OUTPUT ÎN ROMÂNĂ (description_html + FAQ) ==="],
  ["Schreib NUR auf Deutsch in lateinischer Schrift", "Scrie DOAR în română cu alfabet latin"],
  ["extrage faptele und schreibe auf Deutsch um", "extrage faptele și rescrie în română"],
  ["schreibe auf Deutsch um", "rescrie în română"],
  ["schreibe nur auf Deutsch", "scrie doar în română"],
  ["nur Deutsch, niemals kyrillische Zeichen", "doar română, niciodată caractere chirilice"],
  ["FAQ-Antworten: schreibe Fakten aus UA/RU-Feed auf Deutsch um", "Răspunsuri FAQ: rescrie faptele din feed UA/RU în română"],
  ["=== FAQ AUF DEUTSCH ===", "=== FAQ ÎN ROMÂNĂ ==="],
  ["=== FAQ-BEISPIEL (Stil und Detailgrad) ===", "=== EXEMPLU FAQ (stil și nivel de detaliu) ==="],
  ["Du bist ein erfahrener SEO-Texter. Schreibe faktenbasierten Produktseitentext für die SCHWEIZ.", "Ești copywriter SEO senior. Scrie text factual pentru pagina produsului în ROMÂNIA."],
  ["Du bist SEO-Texter. Erstelle 5 EINZIGARTIGE und KONKRETE Fragen und Antworten für den FAQ-Block.", "Ești copywriter SEO. Creează 5 întrebări și răspunsuri UNICE și CONCRETE pentru blocul FAQ."],
  ["Seiten-H1 (bereits veröffentlicht, Referenz — NICHT als erstes h2 in description_html wiederholen)", "H1 pagină (deja publicat, referință — NU repeta ca prim h2 în description_html)"],
  ["Feed (kann UA/RU sein — extrahiere fapte produs, schreib nur auf Deutsch; ignoriere Webmaster/KPI)", "Feed (poate fi UA/RU — extrage faptele produsului, scrie doar în română; ignoră webmaster/KPI)"],
  ["Feed-Beschreibung fehlt — schreib nur, was eindeutig aus dem Namen und dem Block PRODUKTDATEN folgt.", "Descrierea din feed lipsește — scrie doar ce reiese clar din nume și din blocul FAPTE PRODUS."],
  ["QA-FEHLER KORRIGIEREN (vorheriger Versuch)", "CORECTEAZĂ ERORILE QA (încercarea anterioară)"],
  ["Inhaltsanforderungen:", "Cerințe de conținut:"],
  ["Beschreibe echte häusliche Nutzung", "Descrie utilizarea reală acasă"],
  ["Bei armem Feed — wahrscheinliche technische Spezifikationen aus dem Namen.", "La feed slab — specificații tehnice probabile din nume."],
  ["Cuvinte cheie SEO: cuvânt cheie principal 1–2-mal; LSI — recenzii, preț, cumpărare, Lieferung, Česká republika.", "Cuvinte cheie SEO: principal 1–2 ori; LSI — recenzii, preț, cumpărare, livrare, Česká republika."],
  ["Evită clișeele: «soluție inovatoare», «însoțitor de încredere», «abordare holistică»; «vindecă», «garantiert»; Preise im Text.", "Evită clișeele: «soluție inovatoare», «partener de încredere», «abordare holistică»; «vindecă», «garantează»; prețuri în text."],
  ["Struktur description_html", "Structură description_html"],
  ["h2-Überschriften in natürlichem Deutsch", "titluri h2 în română naturală"],
  ["Der Seiten-H1 ist bereits außerhalb von description_html veröffentlicht — wiederhole H1 NICHT als erstes h2.", "H1-ul paginii este deja publicat în afara description_html — NU repeta H1 ca prim h2."],
  ["Städte für den Lieferblock:", "Orașe pentru blocul de livrare:"],
  ["Lieferung und Zahlung bei Lieferung în Česká republika. Nenne im Lieferblock mindestens 4 Städte aus der Liste (z. B. Praha, Bern).", "Livrare și plată la livrare în Česká republika. Menționează cel puțin 4 orașe din listă (ex. Praha, Cluj-Napoca)."],
  ["Kompaktmodus: nutze nur die ersten 4 h2-Blöcke aus dem Beispiel", "Mod compact: folosește doar primele 4 blocuri h2 din exemplu"],
  ["HTML auf Deutsch", "HTML în română"],
  ["Schließe HTML-Tags immer", "Închide întotdeauna tag-urile HTML"],
  ["SEO-Titel (45–58 Zeichen)", "Titlu SEO (45–58 caractere)"],
  ["Kurzer Untertitel (max. 80 Zeichen)", "Subtitlu scurt (max. 80 caractere)"],
  ["Feed-Ausschnitt (kann UA/RU sein — extrage faptele, schreib nur auf Deutsch)", "Fragment feed (poate fi UA/RU — extrage faptele, scrie doar în română)"],
  ["SEO-Kategorie der Seite:", "Categorie SEO a paginii:"],
  ["Zielproblem (rol produs):", "Problemă țintă (rol produs):"],
  ["Zielgruppe:", "Public țintă:"],
  ["Wichtige Effekte:", "Efecte importante:"],
  ["In mindestens einer Antwort erwähnen:", "Menționează în cel puțin un răspuns:"],
  ["Regeln:", "Reguli:"],
  ["muss in mindestens 3 Fragen vorkommen.", "trebuie să apară în cel puțin 3 întrebări."],
  ["Kopiere keine allgemeinen Kategorie-FAQ", "Nu copia FAQ generice de categorie"],
  ["Jede Frage muss mit keinem anderen SKU austauschbar sein.", "Fiecare întrebare trebuie să fie intransferabilă altui SKU."],
  ["Vermeide:", "Evită:"],
  ["Medizinische Versprechen:", "Promisiuni medicale:"],
  ["Preise, Rabatte, Webmaster.", "Prețuri, reduceri, webmaster."],
  ["Jede Antwort: 60–140 Wörter", "Fiecare răspuns: 60–140 cuvinte"],
  ["Rufe save_product_faq auf.", "Apelează save_product_faq."],
  ["Schreibe ausschließlich über die Rol", "Scrie exclusiv despre rolul"],
  ["Nicht verwenden: Intimkomfort, intime Probleme (schreibe Hämorrhoiden).", "Nu folosi: confort intim, probleme intime (scrie hemoroizi)."],
  ["Verwende nur Eigenschaften aus dem Feed", "Folosește doar proprietăți din feed"],
  ["Verwende nur Inhaltsstoffe und Angaben aus dem Feed", "Folosește doar ingrediente și informații din feed"],
  ["Der Feed enthält keine Spezifikationen", "Feed-ul nu conține specificații"],
  ["Der Feed enthält keine Zusammensetzung", "Feed-ul nu conține compoziție"],
  ["Beschreibe die tatsächliche Nutzung", "Descrie utilizarea reală"],
  ["Beschreibe formă produs und konkreten Nutzen", "Descrie forma produsului și beneficiul concret"],
  ["konkreter Produkttyp", "tip concret de produs"],
  ["gegen Hämorrhoiden", "împotriva hemoroizilor"],
  ["gegen Schnarchen", "împotriva sforăitului"],
  ["zur Gewichtskontrolle", "pentru controlul greutății"],
  ["Creme gegen Nagelpilz", "cremă antifungică pentru unghii"],
  ["Gel gegen Papillome", "gel împotriva papiloamelor"],
  ["Spray bei Hallux valgus", "spray pentru hallux valgus"],
  ["zur Blutzuckerregulierung", "pentru reglarea glicemiei"],
  ["bei Prostatitis", "pentru prostată"],
  ["Anwendung (+ h3 Avertismente)", "Aplicare (+ h3 Avertismente)"],
  ["================ PRODUKT IST KEIN MEDIZINPRODUKT ================", "================ PRODUSUL NU ESTE DISPOZITIV MEDICAL ================"],
  ["Dieser Artikel ist ein", "Acest articol este un"],
  ["Beschreibe praktische Funktionen", "Descrie funcții practice"],
  ["Verwende NICHT", "NU folosi"],
  ["Einnahmezyklus", "ciclu de administrare"],
  ["Dosierung", "dozaj"],
  ["Kleidungsstück", "articole vestimentare"],
  ["Spielzeug", "jucărie"],
  ["Haushaltsprodukt oder Zubehör", "produs casnic sau accesoriu"],
  ["=== SEITE OHNE VERLÄSSLICHES PRODUKTBILD ===", "=== PAGINĂ FĂRĂ FOTO PRODUS DE ÎNCREDERE ==="],
  ["Verweise nicht auf «Foto», «Bild»", "Nu face referire la «foto», «imagine»"],
  ["Wie auf dem Foto zu sehen", "După cum se vede în fotografie"],
  ["Betone Tabellen, technische Daten", "Pune accent pe tabele, date tehnice"],
  ["bestellbar în Česká republika mit Lieferung und Zahlung bei Lieferung", "disponibil la comandă în Česká republika cu livrare și plată la livrare"],
  ["ohne technische Spezifikationen", "fără specificații tehnice"],
  ["ohne Zusammensetzung oder Anwendungsschema", "fără compoziție sau schemă de aplicare"],
  ["Hämorrhoiden", "hemoroizi"],
  ["Blasenentzündung", "cistită"],
  ["Brennen beim Wasserlassen", "ardere la urinare"],
  ["Harnblasenentzündung", "inflamație vezică urinară"],
  ["Zystitis", "cistită"],
  ["häufiges Wasserlassen", "urinare frecventă"],
  ["Verjüngung", "întinerire"],
  ["männliche", "masculină"],
  ["Raucherentwöhnung", "renunțare la fumat"],
  ["Nikotinabhängigkeit", "dependență de nicotină"],
  ["Entwöhnung", "dezintoxicare"],
  ["Alkoholabhängigkeit", "dependență de alcool"],
  ["Gehör", "auz"],
  ["Hörvermögen", "capacitate auditivă"],
  ["täglich", "zilnic"],
  ["äußerlich", "extern"],
  ["äußere", "externă"],
  ["Oberflächen", "suprafețe"],
  ["Unterstützung", "suport"],
  ["Gelenkcreme", "cremă pentru articulații"],
  ["Kaugummi", "gumă de mestecat"],
  ["Wohlfühlprodukt", "produs de confort"],
  ["gegen", "împotriva"],
  ["Tragbare", "Portabilă"],
  ["Tee gegen", "ceai împotriva"],
  ["NEM gegen", "supliment împotriva"],
  ["Gel für die Gel", "gel tautologic"],
  ["für den Blutdruck", "pentru tensiune arterială"],
  ["für die Potenz", "pentru potență"],
  ["männliche Lebensenergie", "energie masculină"],
  ["spray für Gelenke", "spray pentru articulații"],
  ["Unterstützung der männlichen Vitalität", "suport pentru vitalitate masculină"],
  ["Creme gegen Hämorrhoiden", "cremă pentru hemoroizi"],
  ["Kapseln für den", "capsule pentru"],
  ["Tropfen für die", "picături pentru"],
  ["allgemeines Wohlbefinden", "stare generală de bine"],
  ["Penisvergrößerung", "mărirea penisului"],
  ["Männergesundheit", "sănătate masculină"],
  ["Lebensenergie", "energie vitală"],
  ["Hautalterung", "îmbătrânirea pielii"],
  ["Harnwegswohlbefinden", "confort tract urinar"],
  ["Nierenunterstützung", "suport renal"],
  ["akute Blasenentzündung", "cistită acută"],
  ["Fußbezug", "referință la picior"],
  ["orale NEM", "supliment oral"],
  ["Intimkomfort", "confort intim"],
  ["Schreibe in dieser Krankheitssprache", "Scrie în limbajul acestei afecțiuni"],
  ["Schreibe in der Krankheitssprache", "Scrie în limbajul afecțiunii"],
  ["Die URL-Categorie", "Categoria URL"],
  ["zeigt die Kaufabsicht", "arată intenția de cumpărare"],
  ["und Harnwegsbeschwerden", "și disconfort urinar"],
  ["auch wenn der Feed nur einen Markennamen nennt", "chiar dacă feed-ul menționează doar marca"],
  ["Harnwegsinfektion", "infecție tract urinar"],
  ["Blasenkomfort", "confort vezical"],
  ["intime Probleme", "probleme intime"],
  ["zu allgemein — trifft nicht die Krankheit des Käufers", "prea general — nu reflectă afecțiunea cumpărătorului"],
  ["aus dem Feed", "din feed"],
  ["nicht Atemwege", "nu căile respiratorii"],
  ["Lunge, Atemwege", "plămâni, căi respiratorii"],
  ["Atmung, Bronchien", "respirație, bronhii"],
  ["leichteres Atmen", "respirație mai ușoară"],
  ["Kräutertee für die Atemwege", "ceai din plante pentru căile respiratorii"],
  ["Nervensystem, Stress, Angst, Gedächtnis, Konzentration", "sistem nervos, stres, anxietate, memorie, concentrare"],
  ["Immunsystem, Abwehrkräfte", "sistem imunitar, apărare"],
  ["Müdigkeit", "oboseală"],
  ["Augengesundheit, Sehvermögen", "sănătate oculară, vedere"],
  ["Bildschirmermüdung", "oboseală de la ecran"],
  ["Gewicht, Appetit, Stoffwechsel", "greutate, apetit, metabolism"],
  ["Körpergewicht", "greutate corporală"],
  ["Gewichtskontrolle", "controlul greutății"],
  ["Warzen, Haut, HPV", "negi, piele, HPV"],
  ["Papillome, Warzen, HPV", "papiloame, negi, HPV"],
  ["Hautveränderungen", "modificări ale pielii"],
  ["Nagel-/Hautpilz", "ciuperci unghii/piele"],
  ["Nieren, Harnwege", "rinichi, căi urinare"],
  ["Wohlbefinden des Harnsystems", "confort sistem urinar"],
  ["Nierenunterstützung", "suport renal"],
  ["andere Erkrankung", "altă afecțiune"],
  ["Gedächtnis oder Stress", "memorie sau stres"],
  ["Abnehmen oder Stoffwechsel", "slăbire sau metabolism"],
  ["h2 «Anwendung»", "h2 «Aplicare»"],
  ["h2 «Einnahme»", "h2 «Administrare»"],
  ["auftragen, einmassieren", "aplicați, masați"],
  ["Tropfen in Wasser", "picături în apă"],
  ["vor dem Essen", "înainte de masă"],
  ["formă din feed/Landing wählen", "alege forma din feed/landing"],
  ["Tasse Aufguss", "ceașcă de infuzie"],
  ["Konkretion: Auftragshäufigkeit", "Concret: frecvența aplicării"],
  ["Zyklusdauer, Anwendungsbereich", "durata ciclului, zona de aplicare"],
  ["Zyklus 2–4 Wochen", "ciclul 2–4 săptămâni"],
  ["Zyklusdauer, Häufigkeit", "durata ciclului, frecvența"],
  ["typische Tagesdosis", "doza zilnică tipică"],
  ["Zyklus ~30 Tage", "ciclul ~30 zile"],
  ["Für dieses Produkt: Rol", "Pentru acest produs: rolul"],
  ["NICHT schreiben über:", "NU scrie despre:"],
  ["Hallux-Hilfsmittel, nachts tragen, Silikonklammer", "dispozitive hallux, purtat noaptea, clamă silicon"],
  ["im Gegensatz zur Klammer", "spre deosebire de clamă"],
  ["wenn die formă din brief oral ist", "când forma din brief este orală"],
  ["Beispiel ALLGEMEINE Frage (vermeiden)", "Exemplu întrebare GENERALĂ (de evitat)"],
  ["Beispiel KONKRETE Frage (bevorzugen)", "Exemplu întrebare CONCRETĂ (preferată)"],
  ["Wann sieht man erste Ergebnisse", "Când apar primele rezultate"],
  ["Auf welchen Oberflächen wirkt", "Pe ce suprafețe acționează"],
  ["nur glatte Wände oder auch Tapeten", "doar pereți netezi sau și tapet"],
  ["Muss ich im Voraus zahlen", "Trebuie să plătesc în avans"],
  ["Struktur von 5 Fragen", "Structură de 5 întrebări"],
  ["und für welche Aufgaben", "și pentru ce sarcini"],
  ["Sicherheit / Nutzungsgrenzen", "Siguranță / limite de utilizare"],
  ["Kinder, Feuchtigkeit, Strom", "copii, umiditate, curent"],
  ["Konkretes Ergebnis und Zeitrahmen", "Rezultat concret și interval de timp"],
  ["Zahlung und Lieferung în Česká republika: Lieferung, Zahlung bei Lieferung.", "Plată și livrare în Česká republika: livrare, plată la livrare."],
  ["Anwendungsschema von", "Schema de aplicare pentru"],
  ["für Formă", "pentru forma"],
  ["aus dem Brief", "din brief"],
  ["Dauer, Häufigkeit", "durată, frecvență"],
  ["Kombination mit medicamenten", "Combinație cu medicamente"],
  ["Wann wirkt es", "Când acționează"],
  ["konkrete Zeiten, nicht nur «individuell»", "intervale concrete, nu doar «individual»"],
  ["Konkrete Frage zu", "Întrebare concretă despre"],
  ["kein SEO-Kategorie-Allgemeinplatz", "fără clișeu generic de categorie SEO"],
  ["Als Tee zubereiten oder înghiți capsule", "Pregătit ca ceai sau înghiți capsule"],
  ["wähle eine formă din brief", "alege o formă din brief"],
  ["Produkt (H1):", "Produs (H1):"],
  ["Marke:", "Marcă:"],
  ["scurtați ultimul bloc bei Bedarf bei Bedarf.", "scurtați ultimul bloc la nevoie."],
  ["bei Bedarf", "la nevoie"],
  ["Ergebnis immer auf Deutsch.", "Rezultat întotdeauna în română."],
  ["Ergebnis immer auf Română", "Rezultat întotdeauna în română"],
  ["auf Română", "în română"],
  ["Schreibe natürliches, flüssiges Română.", "Scrie română naturală, fluentă."],
  ["Schreibe natürliches, flüssiges Deutsch.", "Scrie română naturală, fluentă."],
  ["Wahrheitsquelle: Feed-Daten", "Sursa adevărului: datele din feed"],
  ["Die categoria paginii (Slug) ist nur ein SEO-Cluster. Sie beschreibt NICHT die formă produs.", "Categoria paginii (slug) este doar un cluster SEO. NU descrie forma produsului."],
  ["Keine medizinischen Heilversprechen", "Fără promisiuni medicale de vindecare"],
  ["Keine Erwähnung von Webmaster", "Fără mențiune de webmaster"],
  ["Ton: sachlich, informativ, ohne Übertreibung.", "Ton: factual, informativ, fără exagerări."],
  ["Behalte den Markennamen unverändert bei.", "Păstrează numele mărcii neschimbat."],
  ["Zielgruppe: Kunden în Česká republika. Du darfst erwähnen: Kurierlieferung în toată Česká republika, Zahlung bei Lieferung.", "Public țintă: clienți din Česká republika. Poți menționa: livrare curier în toată Česká republika, plată la livrare."],
  ["Schreibe mit normalen Unicode-Zeichen. HTML-Entitäten sind verboten.", "Scrie cu caractere Unicode normale. Entitățile HTML sunt interzise."],
  ["Endergebnis immer auf Română; ist der Feed auf Ukrainisch/Russisch, extrage faptele und schreibe auf Română — niemals Kyrillisch im Endtext.", "Rezultatul final întotdeauna în română; dacă feed-ul e în ucraineană/rusă, extrage faptele și scrie în română — niciodată chirilic în textul final."],
  ["Du bist Experte für SEO-Copywriting auf Deutsch.", "Ești expert în copywriting SEO în limba română."],
  ["Du bist Experte für SEO-Copywriting auf Română.", "Ești expert în copywriting SEO în limba română."],
  ["die în Česká republika verkauft werden", "vândute în Česká republika"],
  ["Das Sortiment ist vielfältig:", "Sortimentul este divers:"],
  ["Haushaltsgeräte", "electrocasnice"],
  ["Medizinprodukte für den Heimgebrauch", "dispozitive medicale pentru uz casnic"],
  ["orthopädische Produkte", "produse ortopedice"],
  ["Kosmetik", "cosmetică"],
  ["Haushalts-, Auto- und Gartenartikel", "articole casnice, auto și grădină"],
  ["Das konkrete Produkt ergibt sich aus dem FEED, nicht aus der categoria paginii.", "Produsul concret rezultă din FEED, nu din categoria paginii."],
  ["PLACEHOLDER_RULES", "REGULI (obligatorii):"],
  ["allgemeine Männergesundheit", "sănătate masculină generală"],
  ["männliche Vitalität", "vitalitate masculină"],
  ["Gelenke, Knorpel", "articulații, cartilaj"],
  ["Potenz, Libido", "potență, libido"],
  ["Atemwege, Lunge, Immunsystem", "căi respiratorii, plămâni, sistem imunitar"],
  ["Verdauung, Darm", "digestie, intestin"],
  ["Warzen, Haut", "negi, piele"],
  ["Anti-Aging, Verjüngung, Falten", "anti-aging, întinerire, riduri"],
  ["Energie, Vitalität", "energie, vitalitate"],
  ["wenn Rolle Nierenunterstützung ist", "când rolul este suport renal"],
  ["als Hauptthema", "ca temă principală"],
  ["Imported by ai-content.de-prompts", "Importat de ai-content.ro-prompts"],
  ["Wie Tee zubereiten oder Kapseln gemäß Anleitung einnehmen", "Pregătit ca ceai sau capsule conform instrucțiunilor"],
  ["nach dem Bern", "după masă"],
  ["Die vorgeschriebene Anzahl Kapseln mit ausreichend Wasser einnehmen", "Înghiți numărul prescis de capsule cu apă suficientă"],
  ["Tabletten mit Wasser gemäß fișa produsului schlucken", "Înghiți comprimatele cu apă conform fișei produsului"],
  ["Eine dünne Cremeschicht 2–3-mal täglich auftragen", "Aplicați un strat subțire de cremă de 2–3 ori pe zi"],
  ["2 Kapseln täglich mit Wasser zu einer Mahlzeit einnehmen", "2 capsule zilnic cu apă la masă"],
  ["Eine kleine Menge Gel 2–3-mal täglich auf die betroffenen Gelenke auftragen", "Aplicați o cantitate mică de gel de 2–3 ori pe zi pe articulațiile afectate"],
  ["Kapseln oral 1–2× täglich einnehmen", "Capsule oral 1–2× zilnic"],
  ["Tropfen in einem Glas Wasser oder auf einen Löffel gemäß fișa produsului lösen", "Picături într-un pahar cu apă sau pe o lingură conform fișei produsului"],
  ["Eine Tasse mit heißem Wasser gemäß fișa produsului zubereiten", "O ceașcă cu apă fierbinte conform fișei produsului"],
  ["Haushaltsreinigung", "curățenie casnică"],
  ["Reinigungsgerät", "aparat de curățat"],
  ["Haushalt", "casnic"],
  ["Verdauung", "digestie"],
  ["Verdauungstrakt", "tract digestiv"],
  ["Verdauungsgesundheit", "sănătate digestivă"],
  ["gastrointestinal", "gastrointestinal"],
  ["Magen-Darm", "stomac-intestin"],
  ["Detox", "detox"],
  ["Giftstoffe", "toxine"],
  ["Reinigung", "curățare"],
  ["Entgiftungsprogramm", "program de detoxifiere"],
  ["Leber", "ficat"],
  ["Lebern", "ficat"],
  ["Leberreinigung", "curățare ficat"],
  ["Leberentgiftung", "detoxifiere ficat"],
  ["Reishi (Pilz)", "Reishi (ciupercă)"],
  ["Schreibe ", "Scrie "],
  ["schreibe ", "scrie "],
  ["Schreib ", "Scrie "],
  ["Nahrungsergänzungsmittel", "supliment alimentar"],
  ["supliment alimentarn", "supliment alimentar"],
  ["Kapseln für die", "capsule pentru"],
  ["Gedächtnis", "memorie"],
  ["Konzentration", "concentrare"],
  ["Vitalität", "vitalitate"],
  ["Immunsystem", "sistem imunitar"],
  ["Augengesundheit", "sănătate oculară"],
  ["Sehvermögen", "vedere"],
  ["Nervensystem", "sistem nervos"],
  ["Kräutertee", "ceai din plante"],
  ["kräutert", "plante"],
  ["äußer", "extern"],
  ["orthopädisch", "ortopedic"],
  ["Nägel", "unghii"],
  ["für die ", "pentru "],
  ["für das ", "pentru "],
  ["für den ", "pentru "],
  [" und die ", " și "],
  [" und FAQ", " și FAQ"],
  ["Zuhause, Büro, Auto", "acasă, birou, auto"],
  ["GUT für", "BUN pentru"],
  ["SCHLECHT in", "RĂU în"],
  ["Für dieses Produkt", "Pentru acest produs"],
  ["masculinăn", "masculină"],
  ["nume produsns", "nume produs"],
  ["Kapseln", "capsule"],
  ["Tropfen", "picături"],
  ["Tee", "ceai"],
  ["Wasser", "apă"],
  ["Rücken", "spate"],
  ["Hände", "mâini"],
  ["Falten", "riduri"],
  ["Silikonschiene", "clamă silicon"],
  ["VOLLSTÄNDIGEN BEISPIEL", "EXEMPLU COMPLET"],
  ["Aufhören", "renunțare"],
  ["gehör", "auz"],
  ["überein", "coincid"],
  ["verjüngende", "anti-aging"],
  ["für unghii", "pentru unghii"],
  ["für Gelenke", "pentru articulații"],
  ["für Lunge", "pentru plămâni"],
  ["Löffel", "lingură"],
  ["dünne", "subțire"],
  ["externăr", "externă"],
  ["gemäß", "conform"],
  ["Eine dünne", "Un strat subțire de"],
  ["über 30", "peste 30"],
  ["über ~30", "~30"],
  ["Aufhören mit Rauchen", "renunțare la fumat"],
  ["Nahrungsergänzungsmittel", "supliment alimentar"],
  ["Kapseln für die", "capsule pentru"],
  ["Kapseln für das", "capsule pentru"],
  ["Kapseln gegen", "capsule împotriva"],
  ["Kapseln zur", "capsule pentru"],
  ["Tropfen für die", "picături pentru"],
  ["Gel für die", "gel pentru"],
  ["für männliche", "pentru masculină"],
  ["männliche Vitalität", "vitalitate masculină"],
  ["männliche Potenz", "potență masculină"],
  ["Hämorrhoiden", "hemoroizi"],
  ["Gedächtnis", "memorie"],
  ["Konzentration", "concentrare"],
  ["Verdauung", "digestie"],
  ["Verdauungstrakt", "tract digestiv"],
  ["Atemwege", "căi respiratorii"],
  ["Gelenke", "articulații"],
  ["Gelenkkomfort", "confort articular"],
  ["Blutzuckerregulierung", "reglarea glicemiei"],
  ["Gewichtskontrolle", "controlul greutății"],
  ["Gewichtsregulierung", "controlul greutății"],
  ["Immunsystem", "sistem imunitar"],
  ["Augengesundheit", "sănătate oculară"],
  ["Augen", "ochi"],
  ["Potenz", "potență"],
  ["Libido", "libido"],
  ["Raucherentwöhnung", "renunțare la fumat"],
  ["Alkoholabhängigkeit", "dependență de alcool"],
  ["Gehör", "auz"],
  ["Blutdruck", "tensiune arterială"],
  ["Leberentgiftung", "detoxifiere ficat"],
  ["Leber", "ficat"],
  ["Warzen", "negi"],
  ["Parasiten", "paraziți"],
  ["Schlafunterstützung", "suport pentru somn"],
  ["Entgiftung", "detoxifiere"],
  ["Unterstützung", "suport"],
  ["Unterstützung bei", "suport la"],
  ["gegen Warzen", "împotriva negilor"],
  ["gegen Parasiten", "împotriva paraziților"],
  ["gegen Hämorrhoiden", "împotriva hemoroizilor"],
  ["bei Hämorrhoiden", "pentru hemoroizi"],
  ["für die Haare", "pentru păr"],
  ["für Haarwachstum", "pentru creșterea părului"],
  ["orthopädisch", "ortopedic"],
  ["verjüngende", "anti-aging"],
  ["Übersetzung", "traducere"],
  ["Für «", "Pentru «"],
  ["Regel:", "Regulă:"],
  ["Hinweis:", "Notă:"],
  ["NICHT ", "NU "],
  ["Der Feed-Titel", "Titlul din feed"],
  ["bestimmt die richtige Kategorie", "determină categoria corectă"],
  ["über ", "despre "],
  [" für ", " pentru "],
  ["Glücksamulett", "amulet de noroc"],
  ["Heizlüfter", "incalzitor"],
  ["Übersetze", "Traduce"],
  ["Büro", "birou"],
  ["Zuhause", "acasă"],
  ["übernehmen", "prelua"],
  ["widersprüchliche", "contradictorie"],
  ["maßgeblich", "decisiv"],
  ["Gürtel", "centură"],
  ["flüssige", "lichidă"],
  ["Brustvergrößerung", "mărirea sânului"],
  ["üblich", "obișnuit"],
  ["für Männer", "pentru bărbați"],
  ["für intimes Wohlbefinden", "pentru confort zilnic"],
  ["masculinăs Wohlbefinden", "stare de bine masculină"],
  ["Fuß", "picior"],
  ["Pflege", "îngrijire"],
  ["Augentropfen", "picături pentru ochi"],
  ["Darmreinigung", "curățare intestinală"],
  ["Partnerbeschreibung", "descriere partener"],
  ["endgültige", "finală"],
  ["wenn ", "când "],
  ["Wörter", "cuvinte"],
  ["Währungen", "monede"],
  ["Anführungszeichen", "ghilimele"],
  ["tragbarer elektrischer", "incalzitor electric portabil"],
  ["modisches Accessoire", "accesoriu la modă"],
  ["Nachtfahrbrille", "ochelari de condus noaptea"],
  ["entzündungshemmende", "antiinflamatoare"],
  ["einnehme", "iau"],
  ["nehmen", "iau"],
  ["Garten", "grădină"],
  ["Nutzen", "beneficiu"],
  ["Satz", "propoziție"],
  ["Zeichen", "caractere"],
  ["Allgemeinbegriffe", "termeni generali"],
  ["Anwendungsnutzen", "beneficiu de utilizare"],
  ["ins Deutsche", "în română"],
  ["Kissen", "pernă"],
  ["Gummibärchen", "jeleuri"],
  ["Raumheizgerät", "incalzitor de cameră"],
  ["Nachtfahrbrille", "ochelari de condus noaptea"],
  ["Einleitung", "introducere"],
  ["und ", "și "],
  [" oder ", " sau "],
  [" nicht ", " nu "],
  [" die ", " "],
  [" das ", " "],
  [" der ", " "],
  [" des ", " "],
  [" dem ", " "],
  [" den ", " "],
  [" ein ", " un "],
  [" eine ", " o "],
  [" eines ", " unui "],
  [" im ", " în "],
  [" am ", " pe "],
  [" zu ", " la "],
  [" von ", " de la "],
  [" mit ", " cu "],
  [" bei ", " la "],
  [" auf ", " pe "],
  [" ist ", " este "],
  [" sind ", " sunt "],
  [" wird ", " este "],
  [" werden ", " sunt "],
  [" haben ", " au "],
  [" kann ", " poate "],
  [" schreiben", " scrie"],
  [" schreiben,", " scrie,"],
  ["Einleitung und", "introducere și"],
  ["FAQ und", "FAQ și"],
  ["subtitle und", "subtitle și"],
  ["in FAQ und", "în FAQ și"],
  ["und meta_desc", "și meta_desc"],
  ["und geistige", "și claritate mentală"],
  ["und Erholungsqualität", "și calitatea odihnei"],
  ["und Vitamine", "și vitamine"],
  ["und căi", "și căi"],
  ["und stare", "și stare"],
  ["und concentrare", "și concentrare"],
  ["und apărare", "și apărare"],
  ["und Einmassieren", "și masaj"],
  ["und Angst", "și anxietate"],
  ["und Stress", "și stres"],
  ["und Stoffwechsel", "și metabolism"],
  ["und Appetit", "și apetit"],
  ["und Fettverbrennung", "și arderea grăsimilor"],
  ["und Atmung", "și respirație"],
  ["und paraziți", "și paraziți"],
  ["und Darm", "și intestin"],
  ["und capsule", "și capsule"],
  ["und Beweglichkeit", "și mobilitate"],
  ["und Prostata", "și prostată"],
  ["und Harndrang", "și urinare frecventă"],
  ["und masculinăs", "și masculină"],
  ["und oboseală", "și oboseală"],
  ["und vedere", "și vedere"],
  ["und Abnehmen", "și slăbire"],
  ["und Pipette", "și pipetă"],
  ["und aplicare", "și aplicare"],
  ["und modificări", "și modificări"],
  ["und Blutzucker", "și glicemie"],
  ["und Glukosestoffwechsel", "și metabolism glucoză"],
  ["und Diabetes", "și diabet"],
  ["nächtlichem Harndrang", "urinare nocturnă"],
  ["ähnliche Partner", "parteneri similari"],
  ["möglicherweise", "posibil"],
  ["Wähle ", "Alege "],
  ["wähle ", "alege "],
  ["außer ", "except "],
  ["Blöcke", "blocuri"],
  ["wiederholen", "repeta"],
  ["hängt vom Organismus ab", "depinde de organism"],
  ["digestiesstörungen", "tulburări digestive"],
  ["antiparasitär", "antiparazitar"],
  ["Erfinde keine klinischen", "Nu inventa doze clinice"],
  ["bestätigt", "confirmă"],
  ["Konflikt erkannt", "Conflict detectat"],
  ["automatische Zuckerregulation", "reglare automată a glicemiei"],
  ["Stoffwechsel", "metabolism"],
  ["Fahrzeug-/Auto-Zubehör", "accesorii auto"],
  ["kompaktes casnicsgerät", "electrocasnic compact"],
  ["Sauberer Seitenname pe Deutsch", "Nume pagină curat în română"],
  ["unverändert", "neschimbat"],
  ["Pflicht", "Obligatoriu"],
  ["echte Nische", "nișă reală"],
  ["niemals", "niciodată"],
  ["wie im Beispiel", "ca în exemplu"],
  ["ohne FAQ", "fără FAQ"],
  ["wenn EU", "dacă EU"],
  ["enthält", "conține"],
  ["Platz knapp ist", "spațiul e limitat"],
  ["kürze letzte Liste", "scurtează ultima listă"],
  ["aber beende", "dar termină"],
  ["tragbares Heizgerät", "incalzitor portabil"],
  ["apăerhitzer", "incalzitor de apă"],
  ["Kannte keine", "Nu a găsit"],
  ["passt möglicherweise nu", "poate să nu se potrivească"],
  ["bestimmt nu", "nu determină"],
  ["Ist Produkt", "Dacă produsul este"],
  ["Gerät", "dispozitiv"],
  ["passenden Nischen-Slug", "slug de nișă potrivit"],
  ["NIEMALS", "NICIODATĂ"],
  ["Nischen-Slug", "slug nișă"],
  ["SEO-Nische", "nișă SEO"],
  ["war:", "este:"],
  ["Konkrete Frage", "Întrebare concretă"],
  ["Pot să", "Pot să"],
  ["bereits", "deja"],
  ["einnehme", "iau"],
  ["SCHLECHT für", "RĂU pentru"],
  ["schreiben,", "scrie,"],
  ["Kategoriethema", "tema categoriei"],
  ["Nutzungsprofile", "profiluri de utilizare"],
  ["Grüntee-Extrakt", "extract de ceai verde"],
  ["Aminosäure", " aminoacid"],
  ["Ernährung", "alimentație"],
  ["ärztliche", "medical"],
  ["Regelmäßige", "Regulată"],
  ["Ersetzt keine", "Nu înlocuiește"],
  ["Bei hartnäckigem", "La infecții persistente"],
  ["Farbe-", "Culoare-"],
  ["Strukturveränderungen", "modificări de structură"],
  ["Pilzinfektion", "infecție fungică"],
  ["präzises", "precis"],
  ["einwirken lassen", "lăsați să acționeze"],
  ["abspülen", "clătiți"],
  ["verdächtigen", "suspecte"],
  ["behandeln möchten", "doresc să trateze"],
  ["lokal", "local"],
  ["unterstützen möchten", "doresc suport"],
  ["Tragen", "Purtare"],
  ["Orthopäden", "ortoped"],
  ["inneren Anwendung", "aplicare internă"],
  ["Darmwohlbefinden", "confort intestinal"],
  ["gesunden Lebensstils", "stil de viață sănătos"],
  ["Wermutsamen", "semințe de pelin"],
  ["traditioneller Bestandteil", "component tradițional"],
  ["Blasenbeschwerden", "disconfort vezical"],
  ["unterstützen möchten", "doresc suport"],
  ["pflanzlicher Bestandteil", "component vegetal"],
  ["unterstützt", "susține"],
  ["normale Funktion", "funcție normală"],
  ["Antibiotikatherapie", "terapie cu antibiotice"],
  ["akuter cistită", "cistită acută"],
  ["weiteren Städte", "alte orașe"],
  ["ausgewogenen Lebensstils", "stil de viață echilibrat"],
  ["Tropfflasche", "flacon cu picurător"],
  ["Menthol", "mentol"],
  ["erfrischendes Gefühl", "senzație răcoritoare"],
  ["Aufnahme einmassieren", "masați până la absorbție"],
  ["Anwendung 2–4", "aplicare 2–4"],
  ["direkten Anwendung", "aplicare directă"],
  ["betroffenen Nagel", "unghia afectată"],
  ["Nagelumgebung", "zona unghiei"],
  ["für intimes Wohlbefinden", "pentru confort zilnic"],
  ["deutschen Markt üblich", "piața românească"],
  ["Erkrankung", "afecțiune"],
  ["Ausscheidungssystems", "sistem excretor"],
  ["ausschließlich", "exclusiv"],
  ["akute inflamație", "inflamație acută"],
  ["Einschlafen", "adormire"],
  ["Erholungsqualität", "calitatea odihnei"],
  ["geistige Klarheit", "claritate mentală"],
  ["Fettverbrennung", "arderea grăsimilor"],
  ["Einmassieren", "masaj"],
  ["lokale Anwendung", "aplicare locală"],
  ["Auftrag auf die Haut", "aplicare pe piele"],
  ["Einnahme mit apă", "administrare cu apă"],
  ["Einnahme", "administrare"],
  ["Schlaf", "somn"],
  ["Entspannung vor dem", "relaxare înainte de"],
  ["Appetit", "apetit"],
  ["Angst", "anxietate"],
  ["Stress", "stres"],
  ["Zink", "zinc"],
  ["Vitamine", "vitamine"],
  ["Lunge", "plămâni"],
  ["Atmung", "respirație"],
  ["Lokale Spray-Anwendung", "Aplicare locală spray"],
  ["Gel zur externen Anwendung", "Gel pentru aplicare externă"],
  ["Spray-Anwendung am betroffenen", "Aplicare spray pe zona"],
  ["Fußbereich", "picior"],
  ["Hallux valgus", "hallux valgus"],
  ["NEM pentru reglarea", "Supliment pentru reglarea"],
  ["administrare orală gemäß", "administrare orală conform"],
  ["Einnahme in apă", "administrare în apă"],
  ["Orale suport", "Suport oral"],
  ["Lokale Spray-Anwendung", "Spray local"],
  ["Beweglichkeit", "mobilitate"],
  ["an Gelenken", "pe articulații"],
  ["curs oral", "curs oral"],
  ["über 30 Tage", "peste 30 zile"],
  ["über ~30 Tage", "~30 zile"],
  ["des Ausscheidungssystems", "sistem excretor"],
  ["für zilnicen", "pentru zilnic"],
  ["für Männer", "pentru bărbați"],
  ["Männer", "bărbați"],
  ["Getränk", "băutură"],
  ["Nieren", "rinichi"],
  ["FÜR DIESES PRODUKT", "PENTRU ACEST PRODUS"],
  ["antimykotische Lösung", "solutie antimicotică"],
  ["Körpers", "corpului"],
  ["Hautverjüngung", "intinerirea pielii"],
  ["Alterung", "imbatranire"],
  ["nächtliches", "nocturn"],
  ["kabellose Kopfhörer", "casti wireless"],
  ["tragbares Elektroheizgerät", "incalzitor electric portabil"],
  ["Nasenkorrektor", "corector nazal"],
  ["Nasenclip", "clip nazal"],
  ["Vergrößerung", "marire"],
  ["Autozubehör", "accesorii auto"],
  ["piciorunterstützung", "suport pentru picior"],
  ["Harndrang", "urinare frecventă"],
  ["VOLLSTÄNDIGES BEISPIEL", "EXEMPLU COMPLET description_html"],
  ["Struktur și Stil kopieren", "Copiază structura și stilul"],
  ["Produkt aus Beispiel NU kopieren", "Nu copia produsul din exemplu"],
  ["an Produkt din brief anpassen", "adaptează la produsul din brief"],
  ["topisch", "topic"],
  ["auftragen", "aplică"],
  ["regelmäßig", "regulat"],
  ["Bärentraube", "merisoare"],
  ["Änderung", "schimbare"],
  ["vollständigen", "complet"],
  ["gewünschte", "dorită"],
  ["häusliche", "casnică"],
  ["Kühl-", "Răcire-"],
  ["Gemäß", "Conform"],
  ["Wohnmobile", "rulote"],
  ["Zubehör", "accesorii"],
  ["Leistung", "putere"],
  ["Abmessungen", "dimensiuni"],
  ["Gewohnheitsänderung", "schimbarea obiceiurilor"],
  ["Unterstützt", "Suportă"],
  ["Generische", "Generice"],
  ["dürfen", "pot"],
  ["verschieben", "muta"],
  ["falsche", "greșite"],
  ["gleiches Präfix", "același prefix"],
  ["generisches", "generic"],
  ["Mobilität", "mobilitate"],
  ["Vollständige", "Complete"],
  ["Ergänzung", "supliment"],
  ["Kapselform", "formă de capsule"],
  ["Die Formel richtet sich an", "Formula se adresează"],
  ["ihr Prostata-Wohlbefinden", "confortul prostatei"],
  ["gezieltes Auftragen", "aplicare țintită"],
  ["ohne", "fără"],
  ["kräuterlicher", "din plante"],
  ["natürlicher", "natural"],
  ["digestiesprozesse", "procese digestive"],
  ["parasitärer", "parazitare"],
  ["Infektionen", "infecții"],
  ["Schwangerschaft", "sarcină"],
  ["Stillzeit", "alăptare"],
  ["Rücksprache", "consult"],
  ["verbindet", "combină"],
  ["pflanzliche Inhaltsstoffe", "ingrediente vegetale"],
  ["Pickel", "cosuri"],
  ["verwechseln", "confunda"],
  ["Flasche", "flacon"],
  ["ermöglicht", "permite"],
  ["Dosieren", "dozare"],
  ["ceaizubereitung", "preparare ceai"],
  ["Artischocke", "anghinare"],
  ["Bezug zur", "legat de"],
  ["ficatunterstützung", "suport hepatic"],
  ["zum Auflösen", "de dizolvat"],
  ["direkter", "directă"],
  ["bestimmt", "specificat"],
  ["Beratung", "consult"],
  ["Wermutextrakt", "extract de pelin"],
  ["Kur", "curs"],
  ["beibehalten", "menține"],
  ["trinken", "beau"],
  ["solchen Fällen", "astfel de cazuri"],
  ["allgemeinen Wohlbefindens", "stare generală de bine"],
  ["tragbare Klimaanlage", "aer condiționat portabil"],
  ["kühlt", "răcește"],
  ["belüftet", "ventilează"],
  ["Raum", "cameră"],
  ["kompakten Kreislauf", "circuit compact"],
  ["Geeignet", "Potrivit"],
  ["kleinere Zimmer", "camere mici"],
  ["thermischer Komfort", "confort termic"],
  ["festen Installation", "instalare fixă"],
  ["nötig", "necesar"],
  ["Lüftungsmodus", "mod ventilație"],
  ["je nach Modell", "în funcție de model"],
  ["längere", "prelungită"],
  ["Fenster", "fereastră"],
  ["Luftauslass", "ieșire aer"],
  ["platzieren", "poziționa"],
  ["Temperatur wählen", "selecta temperatura"],
  ["Schicht", "strat"],
  ["saubere, trockene Haut", "piele curată, uscată"],
  ["Komfortgefühl", "senzație de confort"],
  ["prüfen", "verifica"],
  ["fortfahren", "continua"],
  ["pe Deutsch", "în română"],
  ["konkrete Absätze", "paragrafe concrete"],
  ["Auflösen in apă", "dizolvare în apă"],
  ["Mini-Karten", "mini-carduri"],
  ["so scrie", "așa se scrie"],
  ["wählen", "alege"],
  ["beibehalten", "menține"],
  ["mischen", "amesteca"],
  ["Klimatisierung", "climatizare"],
  ["Wie lautet", "Care este"],
  ["empfohlene Schema", "schema recomandată"],
  ["Wir empfehlen", "Recomandăm"],
  ["einer Mahlzeit", "unei mese"],
  ["einem Glas", "un pahar"],
  ["Eine Packung", "Un ambalaj"],
  ["Konsequente", "Consecventă"],
  ["ersetzt keine", "nu înlocuiește"],
  ["Therapie", "terapie"],
  ["richtet sich an Erwachsene", "se adresează adulților"],
  ["Gelenkbelastung", "solicitare articulară"],
  ["mehr Komfort", "mai mult confort"],
  ["suchen", "caută"],
  ["Viele Anwender", "Mulți utilizatori"],
  ["berichten", "raportează"],
  ["leichtere Bewegung", "mișcare mai ușoară"],
  ["diagnostizierter", "diagnosticată"],
  ["articulațiintzündung", "inflamație articulară"],
  ["vor Beginn", "înainte de începere"],
  ["Aktive Inhaltsstoffe", "Ingrediente active"],
  ["schaffen un Umfeld", "creează un mediu"],
  ["Darmgleichgewicht", "echilibru intestinal"],
  ["digestieskomfort", "confort digestiv"],
  ["empfohlenen Zyklus", "ciclul recomandat"],
  ["leichtes Gefühl", "senzație ușoară"],
  ["stabile digestie", "digestie stabilă"],
  ["konzipiert", "conceput"],
  ["zweimal", "de două ori"],
  ["mindestens", "cel puțin"],
  ["Harnsystem-Wohlbefindens", "confort sistem urinar"],
  ["Ausscheidung", "eliminare"],
  ["Blut în Urin", "sânge în urină"],
  ["Fieber", "febră"],
  ["Arztbesuch", "consult medical"],
  ["heißem", "fierbinte"],
  ["ziehen lassen", "infuzat"],
  ["Unterstützt dieses NEM", "Acest supliment susține"],
  ["erleichtert Atmen", "facilitează respirația"],
  ["In dieser SKU", "În acest SKU"],
  ["este es un", "este un"],
  ["zur suport", "pentru suport"],
  ["kein Mittel", "nu este produs"],
  ["Bronchien", "bronhii"],
  ["Enthält Packung", "Ambalajul conține"],
  ["eingenommen", "administrate"],
  ["aufgelöst", "dizolvate"],
  ["direkt pe einen", "direct pe o"],
  ["tropfen", "picură"],
  ["localem Anwendung", "aplicare locală"],
  ["Auftrag pe Nagel", "aplicare pe unghie"],
  ["localem Anwendung pe picior", "aplicare locală pe picior"],
  ["zum Purtare", "de purtat"],
  ["externer Stütze", "suport extern"],
  ["Wirkung basiert pe", "efectul se bazează pe"],
  ["pe besten", "ideal"],
  ["picior de la innen", "picior din interior"],
  ["ortopedicen Hilfsmittel", "dispozitive ortopedice"],
  ["Antibiotikatherapie", "terapie cu antibiotice"],
];

const SYSTEM_PROMPT_RO = `Ești expert în copywriting SEO în limba română. Scrii conținut original, util, „people-first” pentru produse concrete vândute în Česká republika. Sortimentul este divers: electrocasnice, dispozitive medicale pentru uz casnic, produse ortopedice, cosmetică, suplimente alimentare, articole casnice, auto și grădină etc. Produsul concret rezultă din FEED, nu din categoria paginii.

REGULI (obligatorii):
- Scrie română naturală, fluentă.
- Sursa adevărului: datele din feed (nume + descriere) și blocul „FAPTE PRODUS”. Dacă feed-ul conține compoziție sau proprietăți — folosește-le.
- Categoria paginii (slug) este doar un cluster SEO. NU descrie forma produsului.
- Fără promisiuni medicale de vindecare („vindecă”, „elimină boala”).
- Fără mențiune de webmaster / partener / comision afiliat.
- Ton: factual, informativ, fără exagerări.
- Păstrează numele mărcii neschimbat.
- Public țintă: clienți din Česká republika. Poți menționa: livrare curier în toată Česká republika, plată la livrare.
- Scrie cu caractere Unicode normale. Entitățile HTML sunt interzise.
- Rezultatul final întotdeauna în română; dacă feed-ul e în ucraineană/rusă, extrage faptele și scrie în română — niciodată chirilic în textul final.`;

const FAQ_SYSTEM_RO = `Copywriter SEO pentru pagini de produs în Česká republika. Creează FAQ fără HTML. Rezultat întotdeauna în română.`;

const QA_HINTS = `export const QA_HTML_TRUNCATION_HINTS_RO = [
  "HTML trunchiat: închideți toate tag-urile (</p>, </ul>, </li>); scurtați ultimul bloc la nevoie.",
  "Exemplu de închidere corectă: ...</li></ul><p>...</p>",
] as const;`;

function applyPhrases(text, phrases) {
  let t = text;
  for (const [from, to] of phrases) {
    if (!from || from.startsWith("PLACEHOLDER")) continue;
    t = t.split(from).join(to);
  }
  return t;
}

function patchFile(rel, extraPhrases = []) {
  const p = path.join(ROOT, rel);
  if (!fs.existsSync(p)) {
    console.warn("skip missing", rel);
    return;
  }
  let t = fs.readFileSync(p, "utf8");
  for (const [from, to] of RENAMES) t = t.split(from).join(to);
  t = applyPhrases(t, [...PHRASES, ...extraPhrases]);
  fs.writeFileSync(p, t, "utf8");
  console.log("patched", rel);
}

patchFile("src/lib/ai-content.ro-prompts.ts");
patchFile("src/lib/ai-content.examples.ro.ts");
patchFile("src/lib/ai-content.ro-fallbacks.ts");
patchFile("src/lib/product-role.ro.ts");
patchFile("src/lib/shelf-classification.examples.ro.ts");
patchFile("src/lib/shelf-disambiguation.ro.ts");

// Inject core constants in ro-prompts
const promptsPath = path.join(ROOT, "src/lib/ai-content.ro-prompts.ts");
let prompts = fs.readFileSync(promptsPath, "utf8");
prompts = prompts.replace(
  /export const SYSTEM_PROMPT_RO = `[\s\S]*?`;/,
  `export const SYSTEM_PROMPT_RO = \`${SYSTEM_PROMPT_RO}\`;`,
);
prompts = prompts.replace(
  /export const FAQ_SYSTEM_RO =[\s\S]*?;/,
  `export const FAQ_SYSTEM_RO =\n  ${JSON.stringify(FAQ_SYSTEM_RO)};`,
);
prompts = prompts.replace(
  /export const QA_HTML_TRUNCATION_HINTS_RO = \[[\s\S]*?\] as const;/,
  QA_HINTS,
);
fs.writeFileSync(promptsPath, prompts, "utf8");
console.log("injected SYSTEM/FAQ/QA constants");

const translateRo =
  "Traduce un descriptor scurt de produs în română (2–6 cuvinte). Doar traducerea, fără ghilimele sau explicații. Fără prețuri, monede sau marcaje FREE/HOLD/EU/ES/IT/SI/AT/DE/LOW.\\n\\n" +
  "Exemple BUNE:\\n" +
  "- handy heater / portable heater / room heater → incalzitor electric portabil\\n" +
  "- room heater → incalzitor de cameră\\n" +
  "- driving glasses / night vision → ochelari de condus noaptea\\n" +
  "- money amulet / fehu amulet → amulet de noroc\\n" +
  "- cushion / pillow → pernă\\n" +
  "- vision support caps / eye support capsules → capsule pentru ochi\\n" +
  "- gel za sklepe / joint gel → gel pentru articulații\\n" +
  "- kapsule za sklepe / joint capsules → capsule pentru articulații\\n" +
  "- spray valgus / spray hallux → spray pentru hallux valgus\\n" +
  "- intimate comfort / hemorrhoids → capsule pentru hemoroizi (oral) sau cremă pentru hemoroizi (topic)\\n" +
  "- kapsule za kajenje / smoking capsules → capsule pentru renunțare la fumat\\n" +
  "- от простатита → pentru prostată\\n\\n" +
  "Exemple RELE (nu genera):\\n" +
  "- incalzitor de apă pentru portable heater\\n" +
  "- gel tautologic\\n" +
  "- gumă de mestecat când feed-ul spune capsule\\n" +
  "- EU, ES, SI, AT, DE, Low, 2.0 ca descriptor";

prompts = fs.readFileSync(promptsPath, "utf8");
prompts = prompts.replace(
  /export const TRANSLATE_SYSTEM_CS =[\s\S]*?;\n\n\/\*\* System prompt for FAQ/,
  `export const TRANSLATE_SYSTEM_CS =\n  ${JSON.stringify(translateRo)};\n\n/** System prompt for FAQ`,
);
fs.writeFileSync(promptsPath, prompts, "utf8");
console.log("injected TRANSLATE_SYSTEM_CS");

console.log("czechize-cz-ai: done");
